# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5233f05d-3a02-4d80-9270-e2535a6a102f";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."nixenc".device = "/dev/disk/by-uuid/88911077-7e3f-4c80-a2b7-f9b52a089028";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5233f05d-3a02-4d80-9270-e2535a6a102f";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5233f05d-3a02-4d80-9270-e2535a6a102f";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/5233f05d-3a02-4d80-9270-e2535a6a102f";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E2E3-D9DD";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/912ff038-8ab0-4853-8fc0-d23986e127e5"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
