# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1382e911-5222-4afa-a59e-0705555906e9";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" "space_cache" ];
    };

  boot.initrd.luks.devices."btrfscrypt".device = "/dev/disk/by-uuid/1898f4d4-b357-490d-8596-29adcde30e34";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1382e911-5222-4afa-a59e-0705555906e9";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" "space_cache" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1382e911-5222-4afa-a59e-0705555906e9";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" "space_cache" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/1382e911-5222-4afa-a59e-0705555906e9";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" "space_cache" ];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3404-F280";
      fsType = "vfat";
    };

  swapDevices = [ ];
  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # High-DPI console
  console.font = lib.mkDefault "${pkgs.terminus_font}/share/consolefonts/ter-u28n.psf.gz";
}
