#!/usr/bin/env sh


# This script allows to use ctrl+PgUp/PgDn for switching workspaces

function navigate(){
        nameOfWorkspaces=""
        currentWorkspace=$(swaymsg -t get_workspaces |jq ".[] | select(.focused).num")
        echo $1
        case $1 in
                "next")
                        num=$((currentWorkspace+1))
                        [ $num -ge 6 ] && num=1
                        swaymsg workspace number $num $nameOfWorkspaces;;
                "prev")
                        num=$((currentWorkspace-1))
                        [ $num -le 0 ] && num=5
                        swaymsg workspace number $num $nameOfWorkspaces;;
        esac
}

function move(){
        nameOfWorkspaces=""
        currentWorkspace=$(swaymsg -t get_workspaces |jq ".[] | select(.focused).num")
        echo $1
        case $1 in
                "next")
                        num=$((currentWorkspace+1))
                        [ $num -ge 6 ] && num=1
                        swaymsg move container to workspace number $num $nameOfWorkspaces;;
                "prev")
                        num=$((currentWorkspace-1))
                        [ $num -le 0 ] && num=5
                        swaymsg move container to workspace number $num $nameOfWorkspaces;;
        esac
}

case $1 in
        "navigate")
                case $2 in
                        "next")
                                navigate next;;
                        "prev")
                                navigate prev;;
                esac;;
        "move")
                case $2 in
                        "next")
                                move next;;
                        "prev")
                                move prev;;
                esac;;
esac
